spring.application.name=mailserv
# Puerto de la aplicación
server.port=8081

# Configuración SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dleonc2499@gmail.com
spring.mail.password=mask wyib zdne eryk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Opcional: más detalles en consola
logging.level.org.springframework.mail=DEBUG

#evita reiniciar la aplicación cada vez que modifiques una plantilla HTML.
spring.thymeleaf.cache=false
